// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrpfR7hMuQ_cQplUpJFJnbI94NiH-2b_Q',
    appId: '1:289829214507:web:f63317e269456c40474d6e',
    messagingSenderId: '289829214507',
    projectId: 'subook-59546',
    authDomain: 'subook-59546.firebaseapp.com',
    databaseURL: 'https://subook-59546-default-rtdb.firebaseio.com',
    storageBucket: 'subook-59546.firebasestorage.app',
    measurementId: 'G-GTK639VGGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHxb8S5DEu1BcgHgugHQmztWymE6GoolQ',
    appId: '1:289829214507:android:3c2146a2872555d5474d6e',
    messagingSenderId: '289829214507',
    projectId: 'subook-59546',
    databaseURL: 'https://subook-59546-default-rtdb.firebaseio.com',
    storageBucket: 'subook-59546.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrpfR7hMuQ_cQplUpJFJnbI94NiH-2b_Q',
    appId: '1:289829214507:web:981574311051497c474d6e',
    messagingSenderId: '289829214507',
    projectId: 'subook-59546',
    authDomain: 'subook-59546.firebaseapp.com',
    databaseURL: 'https://subook-59546-default-rtdb.firebaseio.com',
    storageBucket: 'subook-59546.firebasestorage.app',
    measurementId: 'G-DZN73DGYHD',
  );
}
